version: '3.8'

services:
  finance_db:
    image: postgres:15
    container_name: finance_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: finance_db
    ports:
      - 5432:5432
    volumes:
      - db-expanse-tracker-app:/var/lib/postgresql/data

volumes:
  db-expanse-tracker-app:
